baseURL = 'https://abbas.is-a.dev/'
languageCode = 'en-us'
title = 'Ctrl-Shift-Abbas'
theme = 'ananke'

[pagination]
pagerSize = 20

[services]
  [services.disqus]
    shortname = 'ablog-4'

[markup.highlight]
style = "github-dark"

[params]
  author = "Abbas Raza"
  info = "Tech. Music. Philosophy."
  description = "Ctrl-Shift-Abbas: Abbas' digital playground"
  keywords = "tech, music, philosophy, blog, personal"
  avatarurl = "images/avatar.jpg"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2024

  enableTwemoji = true
  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/abbas-rz/"

[[params.social]]
  name = "Bluesky"
  icon = "fa-brands fa-bluesky fa-2x"
  weight = 3
  url = "https://bsky.app/profile/4bbxs.bsky.social"

[[params.social]]
  name = "Instagram"
  icon = "fa-brands fa-instagram fa-2x"
  weight = 3
  url = "https://www.instagram.com/4bbvs/"

[[params.social]]
  name = "Discord"
  icon = "fa-brands fa-discord fa-2x"
  weight = 3
  url = "https://discord.com/users/4bbxs"
[[params.social]]
  name = "Linkedin"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 3
  url = "linkedin.com/in/abbas-raza-7b8516218"
[[params.social]]
  name = "Email"
  icon = "fa fa-envelope fa-2x"
  weight = 3
  url = "mailto:Reach@abbas.is-a.dev?body=referred%20to%20by%20the%20website"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[sitemap]
  filename = "sitemap.xml"
  changefreq = "weekly"
  priority = 0.5